### ISSUE TITLE
performance tuning

### ISSUE THREAD

**Issue by alex-nexus** [alejandc/music-service-api#19]
what are some of the endpoint you would like to enhance the performance?

**Comment by alejandc** [comment]
Hi Alex, ie I would like to add pagination to the following endpoints to enhance the performance:

- GET    /albums/all
- GET    /artists
- GET    /playlists

I implemented pagination with kaminari gem for these endpoints, PR: https://github.com/alejandc/music-service-api/pull/21

Also add includes method to allow eager loading and reduce the number of queries to the database.

**Comment by alex-nexus** [comment]
great!
