### ISSUE TITLE
deletions

### ISSUE THREAD

**Issue by alex-nexus** [alejandc/music-service-api#9]
what happens when deleting an artists with an album?

what happens when deleting an album with songs?

**Comment by alejandc** [comment]
There are a cascade functionality that when you delete an artist you also delete the albums and songs that are related with each album of the artist.
So if you only delete one or more albums from any artist also you will delete the songs related with each album
And also will delete the relation between songs and playlists.

**Comment by alex-nexus** [comment]
ok
